// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicApp.Web.Data;

#nullable disable

namespace MusicApp.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260803050217_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusicApp.Web.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pop"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jazz"
                        });
                });

            modelBuilder.Entity("MusicApp.Web.Models.Singer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Singers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://via.placeholder.com/150?text=Adele",
                            Name = "Adele"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://via.placeholder.com/150?text=Ed+Sheeran",
                            Name = "Ed Sheeran"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://via.placeholder.com/150?text=Aurora",
                            Name = "Aurora"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://via.placeholder.com/150?text=Freddie+King",
                            Name = "Freddie King"
                        });
                });

            modelBuilder.Entity("MusicApp.Web.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SingerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SingerId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            SingerId = 1,
                            Title = "Hello"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            SingerId = 1,
                            Title = "Rolling in Deep"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            SingerId = 2,
                            Title = "Shape of You"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            SingerId = 2,
                            Title = "Perfect"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            SingerId = 3,
                            Title = "Runaway"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            SingerId = 3,
                            Title = "Running to Sea"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            SingerId = 3,
                            Title = "Half Light"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            SingerId = 4,
                            Title = "Hide Away"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            SingerId = 4,
                            Title = "You Got What"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            SingerId = 1,
                            Title = "Someone Like You"
                        });
                });

            modelBuilder.Entity("MusicApp.Web.Models.Song", b =>
                {
                    b.HasOne("MusicApp.Web.Models.Category", "Category")
                        .WithMany("Songs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusicApp.Web.Models.Singer", "Singer")
                        .WithMany("Songs")
                        .HasForeignKey("SingerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Singer");
                });

            modelBuilder.Entity("MusicApp.Web.Models.Category", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("MusicApp.Web.Models.Singer", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
